package com.godtrue.jvm;

/**
 * @description：
 * @author：qianyingjie1
 * @create：2019-11-04
 */
public class ShowClassLoading {
    public static void main(String[] args) {
        System.out.println("\n\n\nuse -XX:+TraceClassLoading Trace loading of classes\n\n\n");
    }
}


/*

1：正确的配置方式，注意，错一个符号都不行，+ 表示开启此配置项

-XX:+TraceClassLoading
     Trace loading of classes

2：- 表示不开始此配置项

-XX:-TraceClassLoading
     Trace loading of classes

3：没有使用个 + 或者 - 会报错

-XX:TraceClassLoading

Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Missing +/- setting for VM option 'TraceClassLoading'

*/


/*


从类加载的日志中可以了解到入下信息：

1：最简单的java程序也会加入许多的类
2：最简单的java程序只会加载两个jar包下的类，分别是 jdk1.8.0_162\jre\lib\rt.jar 和 charsets.jar
3：越是上层的类或接口，是越早被加载的，比如：所有类的父类 java.lang.Object
4：rt.jar 这个jar非常的重要，所有核心的基础类都在这里了

[Opened C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]

[Loaded java.lang.Object from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.Serializable from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Comparable from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.CharSequence from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.String from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.reflect.AnnotatedElement from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.reflect.GenericDeclaration from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.reflect.Type from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Class from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Cloneable from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ClassLoader from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.System from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Throwable from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Error from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ThreadDeath from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Exception from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.RuntimeException from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.SecurityManager from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.ProtectionDomain from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.AccessControlContext from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.SecureClassLoader from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ReflectiveOperationException from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ClassNotFoundException from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.LinkageError from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.NoClassDefFoundError from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ClassCastException from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ArrayStoreException from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.VirtualMachineError from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.OutOfMemoryError from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.StackOverflowError from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.IllegalMonitorStateException from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ref.Reference from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ref.SoftReference from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ref.WeakReference from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ref.FinalReference from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ref.PhantomReference from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.Cleaner from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ref.Finalizer from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Runnable from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Thread from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Thread$UncaughtExceptionHandler from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ThreadGroup from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Map from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Dictionary from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Hashtable from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Properties from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.reflect.AccessibleObject from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.reflect.Member from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.reflect.Field from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.reflect.Parameter from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.reflect.Executable from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.reflect.Method from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.reflect.Constructor from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.MagicAccessorImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.MethodAccessor from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.MethodAccessorImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.ConstructorAccessor from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.ConstructorAccessorImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.DelegatingClassLoader from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.ConstantPool from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.FieldAccessor from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.FieldAccessorImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.UnsafeFieldAccessorImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.UnsafeStaticFieldAccessorImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.annotation.Annotation from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.CallerSensitive from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.invoke.MethodHandle from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.invoke.DirectMethodHandle from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.invoke.MemberName from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.invoke.MethodHandleNatives from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.invoke.LambdaForm from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.invoke.MethodType from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.BootstrapMethodError from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.invoke.CallSite from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.invoke.ConstantCallSite from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.invoke.MutableCallSite from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.invoke.VolatileCallSite from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Appendable from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.AbstractStringBuilder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.StringBuffer from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.StringBuilder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.Unsafe from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.AutoCloseable from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.Closeable from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.InputStream from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.ByteArrayInputStream from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.File from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.URLClassLoader from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.URL from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.jar.Manifest from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.Launcher from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.Launcher$AppClassLoader from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.Launcher$ExtClassLoader from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.CodeSource from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.StackTraceElement from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.Buffer from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Boolean from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Character from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Number from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Float from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Double from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Byte from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Short from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Integer from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Long from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.NullPointerException from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ArithmeticException from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.ObjectStreamField from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Comparator from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.String$CaseInsensitiveComparator from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.Guard from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.Permission from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.BasicPermission from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.RuntimePermission from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.AccessController from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.reflect.ReflectPermission from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.PrivilegedAction from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.ReflectionFactory$GetReflectionFactoryAction from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.cert.Certificate from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Iterable from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Collection from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.List from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.RandomAccess from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.AbstractCollection from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.AbstractList from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Vector from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Stack from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.ReflectionFactory from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ref.Reference$Lock from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ref.Reference$ReferenceHandler from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.InterruptedException from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.ArrayList from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Collections from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Set from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.AbstractSet from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Collections$EmptySet from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Collections$EmptyList from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.AbstractMap from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Collections$EmptyMap from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Collections$UnmodifiableCollection from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Collections$UnmodifiableList from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Collections$UnmodifiableRandomAccessList from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ref.ReferenceQueue from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ref.ReferenceQueue$Null from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ref.ReferenceQueue$Lock from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.JavaLangRefAccess from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ref.Reference$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.SharedSecrets from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.IncompatibleClassChangeError from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.NoSuchMethodError from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.Reflection from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.HashMap from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Map$Entry from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.HashMap$Node from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.VM from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Hashtable$Entry from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Math from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ref.Finalizer$FinalizerThread from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.charset.Charset from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.charset.spi.CharsetProvider from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.FastCharsetProvider from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.StandardCharsets from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.util.PreHashedMap from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.StandardCharsets$Aliases from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.StandardCharsets$Classes from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.StandardCharsets$Cache from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ThreadLocal from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.concurrent.atomic.AtomicInteger from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Class$3 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Class$ReflectionData from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Class$Atomic from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.generics.repository.AbstractRepository from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.generics.repository.GenericDeclRepository from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.generics.repository.ClassRepository from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Class$AnnotationData from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.annotation.AnnotationType from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.WeakHashMap from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ClassValue$ClassValueMap from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.reflect.Modifier from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.LangReflectAccess from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.reflect.ReflectAccess from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Arrays from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.charset.Charset$ExtendedProviderHolder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.charset.Charset$ExtendedProviderHolder$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]

[Opened C:\Program Files\Java\jdk1.8.0_162\jre\lib\charsets.jar]

[Loaded sun.nio.cs.AbstractCharsetProvider from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.ext.ExtendedCharsets from C:\Program Files\Java\jdk1.8.0_162\jre\lib\charsets.jar]
[Loaded java.lang.Class$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.ReflectionFactory$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.NativeConstructorAccessorImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.DelegatingConstructorAccessorImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.SortedMap from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.NavigableMap from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.TreeMap from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.ASCIICaseInsensitiveComparator from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.TreeMap$Entry from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.HistoricallyNamedCharset from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.ext.GBK from C:\Program Files\Java\jdk1.8.0_162\jre\lib\charsets.jar]
[Loaded java.lang.StringCoding from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ThreadLocal$ThreadLocalMap from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ThreadLocal$ThreadLocalMap$Entry from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.StringCoding$StringDecoder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.ext.DoubleByte from C:\Program Files\Java\jdk1.8.0_162\jre\lib\charsets.jar]
[Loaded sun.nio.cs.ext.DelegatableDecoder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\charsets.jar]
[Loaded sun.nio.cs.ArrayDecoder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.charset.CharsetDecoder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.ext.DoubleByte$Decoder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\charsets.jar]
[Loaded java.nio.charset.CodingErrorAction from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Hashtable$EntrySet from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Collections$SynchronizedCollection from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Collections$SynchronizedSet from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Objects from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Enumeration from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Iterator from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Hashtable$Enumerator from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Runtime from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.Version from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.FileInputStream from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.FileDescriptor from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.JavaIOFileDescriptorAccess from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.FileDescriptor$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.Flushable from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.OutputStream from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.FileOutputStream from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.FilterInputStream from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.BufferedInputStream from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.concurrent.atomic.AtomicReferenceFieldUpdater from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.PrivilegedExceptionAction from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.misc.ReflectUtil from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.FilterOutputStream from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.PrintStream from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.BufferedOutputStream from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.Writer from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.OutputStreamWriter from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.StreamEncoder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.security.action.GetPropertyAction from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.Unicode from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.UTF_8 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.ArrayEncoder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.charset.CharsetEncoder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.UTF_8$Encoder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.ByteBuffer from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.HeapByteBuffer from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.Bits from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.ByteOrder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.concurrent.atomic.AtomicLong from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.JavaNioAccess from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.Bits$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.BufferedWriter from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.DefaultFileSystem from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.FileSystem from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.WinNTFileSystem from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.ExpiringCache from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.LinkedHashMap from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.ExpiringCache$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Enum from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.File$PathStatus from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.file.Watchable from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.file.Path from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.StringCoding$StringEncoder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.ext.DoubleByte$Encoder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\charsets.jar]
[Loaded java.lang.Readable from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.CharBuffer from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.HeapCharBuffer from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.charset.CoderResult from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.charset.CoderResult$Cache from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.charset.CoderResult$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.charset.CoderResult$2 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ClassLoader$3 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.ExpiringCache$Entry from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.LinkedHashMap$Entry from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ClassLoader$NativeLibrary from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Terminator from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.SignalHandler from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Terminator$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.Signal from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.NativeSignalHandler from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Integer$IntegerCache from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.OSEnvironment from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.io.Win32ErrorMode from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.JavaLangAccess from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.System$2 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.IllegalArgumentException from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Compiler from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Compiler$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.URLStreamHandlerFactory from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.Launcher$Factory from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.security.util.Debug from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ClassLoader$ParallelLoaders from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.WeakHashMap$Entry from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Collections$SetFromMap from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.WeakHashMap$KeySet from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.JavaNetAccess from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.URLClassLoader$7 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.StringTokenizer from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.Launcher$ExtClassLoader$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.MetaIndex from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.Reader from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.BufferedReader from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.InputStreamReader from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.FileReader from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.StreamDecoder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.UTF_8$Decoder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.reflect.Array from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Locale from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.util.locale.LocaleObjectCache from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Locale$Cache from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.concurrent.ConcurrentMap from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.concurrent.ConcurrentHashMap from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.concurrent.locks.Lock from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.concurrent.locks.ReentrantLock from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.concurrent.ConcurrentHashMap$Segment from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.concurrent.ConcurrentHashMap$Node from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.concurrent.ConcurrentHashMap$CounterCell from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.concurrent.ConcurrentHashMap$CollectionView from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.concurrent.ConcurrentHashMap$KeySetView from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.concurrent.ConcurrentHashMap$ValuesView from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.concurrent.ConcurrentHashMap$EntrySetView from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.util.locale.BaseLocale from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.util.locale.BaseLocale$Cache from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.util.locale.BaseLocale$Key from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.util.locale.LocaleObjectCache$CacheEntry from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Locale$LocaleKey from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.util.locale.LocaleUtils from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.CharacterData from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.CharacterDataLatin1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.HashMap$TreeNode from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.FileInputStream$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.net.www.ParseUtil from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.BitSet from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.Parts from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.URLStreamHandler from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.net.www.protocol.file.Handler from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.JavaSecurityAccess from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.ProtectionDomain$JavaSecurityAccessImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.JavaSecurityProtectionDomainAccess from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.ProtectionDomain$2 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.ProtectionDomain$Key from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.Principal from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.HashSet from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.URLClassPath from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.net.www.protocol.jar.Handler from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.Launcher$AppClassLoader$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.SystemClassLoaderAction from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.InternalError from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.instrument.Instrumentation from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.instrument.InstrumentationImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.instrument.TransformerManager from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.instrument.TransformerManager$TransformerInfo from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.URLClassLoader$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.net.util.URLUtil from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.URLClassPath$3 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.URLClassPath$Loader from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.URLClassPath$JarLoader from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.zip.ZipConstants from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.zip.ZipFile from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.JavaUtilZipFileAccess from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.zip.ZipFile$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.ThreadLocalCoders from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.ThreadLocalCoders$Cache from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.ThreadLocalCoders$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.ThreadLocalCoders$2 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.URLClassPath$JarLoader$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.FileURLMapper from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.jar.JarFile from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.JavaUtilJarAccess from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.jar.JavaUtilJarAccessImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.charset.StandardCharsets from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.US_ASCII from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.ISO_8859_1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.UTF_16BE from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.UTF_16LE from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.UTF_16 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Queue from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Deque from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.ArrayDeque from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.zip.ZipCoder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.PerfCounter from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.Perf$GetPerfAction from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.Perf from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.PerfCounter$CoreCounters from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.ch.DirectBuffer from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.MappedByteBuffer from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.DirectByteBuffer from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.LongBuffer from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.nio.DirectLongBufferU from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.JarIndex from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.zip.ZipEntry from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.jar.JarEntry from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.jar.JarFile$JarFileEntry from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.zip.ZipFile$ZipFileInputStream from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.AbstractSequentialList from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.LinkedList from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.LinkedList$Node from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.ExtensionDependency from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.IOUtils from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.zip.Inflater from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.zip.ZStreamRef from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.zip.InflaterInputStream from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.zip.ZipFile$ZipFileInflaterInputStream from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.URLClassPath$FileLoader from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.Resource from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.URLClassPath$JarLoader$2 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.jar.Attributes from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.jar.Manifest$FastInputStream from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.jar.Attributes$Name from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.jar.JarVerifier from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.CodeSigner from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.jar.JarVerifier$3 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.ByteArrayOutputStream from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Package from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.security.util.SignatureFileVerifier from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.AlgorithmConstraints from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.security.util.AbstractAlgorithmConstraints from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.security.util.DisabledAlgorithmConstraints from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.security.util.AlgorithmDecomposer from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.regex.Pattern from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.regex.Pattern$Node from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.regex.Pattern$4 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.regex.Pattern$LastNode from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.regex.Pattern$GroupHead from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.regex.Pattern$CharProperty from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.regex.Pattern$BmpCharProperty from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.regex.Pattern$Single from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.regex.Pattern$SliceNode from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.regex.Pattern$Slice from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.regex.Pattern$Begin from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.regex.Pattern$First from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.regex.Pattern$Start from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.regex.Pattern$TreeInfo from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.regex.ASCII from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.regex.Pattern$SliceI from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.regex.Pattern$BranchConn from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.regex.Pattern$Branch from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.security.util.AbstractAlgorithmConstraints$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.Security from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.Security$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Properties$LineReader from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.ArrayList$SubList from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.ListIterator from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.ArrayList$SubList$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.security.util.DisabledAlgorithmConstraints$Constraints from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.regex.Pattern$BnM from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.regex.MatchResult from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.regex.Matcher from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.Arrays$ArrayList from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.AbstractList$Itr from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.security.util.DisabledAlgorithmConstraints$Constraint from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.security.util.DisabledAlgorithmConstraints$DisabledConstraint from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.security.util.DisabledAlgorithmConstraints$KeySizeConstraint from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.security.util.DisabledAlgorithmConstraints$Constraint$Operator from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.security.util.DisabledAlgorithmConstraints$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.security.util.ManifestEntryVerifier from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.ByteBuffered from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.PermissionCollection from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.Permissions from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.URLConnection from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.net.www.URLConnection from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.net.www.protocol.file.FileURLConnection from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.net.www.MessageHeader from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.FilePermission from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.FilePermission$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.FilePermissionCollection from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.AllPermission from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.UnresolvedPermission from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.security.BasicPermissionCollection from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded com.intellij.rt.execution.application.AppMainV2$Agent from file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%202017.2.2/lib/idea_rt.jar]
[Loaded sun.instrument.InstrumentationImpl$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.NativeMethodAccessorImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.reflect.DelegatingMethodAccessorImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded com.intellij.rt.execution.application.AppMainV2 from file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%202017.2.2/lib/idea_rt.jar]
[Loaded com.intellij.rt.execution.application.AppMainV2$1 from file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%202017.2.2/lib/idea_rt.jar]
[Loaded java.util.concurrent.ConcurrentHashMap$ForwardingNode from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.reflect.InvocationTargetException from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.NoSuchMethodException from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.Socket from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.invoke.MethodHandleImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.SocketAddress from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.InetSocketAddress from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.InetAddress from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.invoke.MethodHandleImpl$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.InetSocketAddress$InetSocketAddressHolder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.function.Function from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.invoke.MethodHandleImpl$2 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.security.action.GetBooleanAction from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.invoke.MethodHandleImpl$3 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.InetAddress$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ClassValue from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.invoke.MethodHandleImpl$4 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ClassValue$Entry from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ClassValue$Identity from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.ClassValue$Version from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.invoke.MemberName$Factory from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.invoke.MethodHandleStatics from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.invoke.MethodHandleStatics$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.InetAddress$InetAddressHolder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.PostVMInitHook from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.InetAddress$Cache from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.InetAddress$Cache$Type from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.InetAddressImplFactory from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.usagetracker.UsageTrackerClient from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.concurrent.atomic.AtomicBoolean from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.InetAddressImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.Inet6AddressImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.usagetracker.UsageTrackerClient$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.net.spi.nameservice.NameService from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.InetAddress$2 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.net.util.IPAddressUtil from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.usagetracker.UsageTrackerClient$4 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.Inet4Address from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.usagetracker.UsageTrackerClient$2 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded jdk.internal.util.EnvUtils from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.SocksConsts from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.usagetracker.UsageTrackerClient$3 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.SocketOptions from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.SocketImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.AbstractPlainSocketImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.PlainSocketImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.SocksSocketImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.AbstractPlainSocketImpl$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.PlainSocketImpl$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.FloatingDecimal from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.FloatingDecimal$BinaryToASCIIConverter from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.FloatingDecimal$ExceptionalBinaryToASCIIBuffer from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.FloatingDecimal$BinaryToASCIIBuffer from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.FloatingDecimal$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.FloatingDecimal$ASCIIToBinaryConverter from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.FloatingDecimal$PreparedASCIIToBinaryBuffer from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.FloatingDecimal$ASCIIToBinaryBuffer from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.DualStackPlainSocketImpl from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.Inet6Address from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.Inet6Address$Inet6AddressHolder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.SocksSocketImpl$3 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.ProxySelector from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.net.spi.DefaultProxySelector from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.net.spi.DefaultProxySelector$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.net.NetProperties from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.net.NetProperties$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.io.FileOutputStream$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.URI from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.URI$Parser from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.net.spi.DefaultProxySelector$NonProxyInfo from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.net.spi.DefaultProxySelector$3 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.Proxy from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.Proxy$Type from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.util.ArrayList$Itr from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.net.NetHooks from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.Socket$2 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.net.SocketInputStream from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.nio.cs.US_ASCII$Decoder from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.launcher.LauncherHelper from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded sun.misc.URLClassPath$FileLoader$1 from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded com.godtrue.jvm.ShowClassLoading from file:/D:/workspace_test/jvm/jvmTest/target/classes/]
[Loaded sun.launcher.LauncherHelper$FXHelper from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Class$MethodArray from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Void from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]



use -XX:+TraceClassLoading Trace loading of classes



[Loaded java.lang.Shutdown from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]
[Loaded java.lang.Shutdown$Lock from C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar]

Process finished with exit code 0

 */
